server:
  port: 8082

spring:
  datasource:
    url: jdbc:postgresql://localhost:5422/ab180-recruit
    username: admin
    password: 1234

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    showSql: true
    properties:
      default_batch_fetch_size: 1000
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
        jdbc:
          lob:
            non_contextual_creation: true